name: Build the ADI kernel matrix

on:
  push:
    branches:
      - 'staging/**'
  pull_request:
    branches:
      - main
      - master
      - '20[1-9][0-9]_R[1-9]'

jobs:
  checkpatch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    env:
      BUILD_TYPE: checkpatch
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: Run Linux's checkpatch script
      run: ./ci/travis/run-build.sh

  dtb_build_test:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: dtb_build_test
      DTS_FILES: "arch/arm/boot/dts/zynq-*.dts
                  arch/arm/boot/dts/socfpga_*.dts
                  arch/arm64/boot/dts/xilinx/zynqmp-*.dts
                  arch/microblaze/boot/dts/*.dts
                  arch/nios2/boot/dts/*.dts"
    steps:
    - uses: actions/checkout@v2
    - name: Build device-trees
      run: ./ci/travis/run-build.sh
